### ISSUE TITLE
Bekräfta lösenord när man skapar användarkonto fungerar inte

### ISSUE THREAD

**Issue by ib222dp** [th222fa/1DV450_APIRegistration#1]
Jag kunde skapa ett användarkonto fastän jag skrev två olika saker i Lösenord och Bekräfta lösenord.

**Comment by WheresMarco** [comment]
Upplever samma. Du har stängt av valideringen på `has_secure_password` i modellen för User vilket gör att den inte kollar om lösenorden stämmer bland annat. Testa att sätta den till true så ska det nog fungera bättre.

**Comment by Guepen** [comment]
miss av mig... Vill ju ha mina felmeddelande på svenska därav har jag satt false på has_secure_password. Jag har åtgärdat detta med mer validering

**Comment by 1dv450** [comment]
:+1:
