### ISSUE TITLE
Inloggad användare kan inte skapa/ta bort API-nyckel

### ISSUE THREAD

**Issue by ib222dp** [th222fa/1DV450_APIRegistration#4]
När jag klickade på "registrera/avregistrera API-nyckel"-knapparna fick jag felmeddelandet "Routing error, uninitialized constant ApiKeysController"

**Comment by WheresMarco** [comment]
Jag får samma fel när jag loggar in med tester-kontot och försöker trycka på "Registrera API-nyckel"-knappen. 

Men jag får en nyckel när jag skapar en ny användare, dock får jag samma felmeddelande när jag försöker avregistrera en nyckel.

**Comment by Guepen** [comment]
Har missat att pusha controllern för Api-nyckel. Detta är åtgärdat
