### ISSUE TITLE
Administratör tar bort användarkonto

### ISSUE THREAD

**Issue by ib222dp** [th222fa/1DV450_APIRegistration#6]
Enligt kraven för applikationen ska en administratör kunna ta bort användares API-nycklar, inte radera deras användarkonton.

**Comment by WheresMarco** [comment]
I min applikation har jag gjort samma sak. Raderar man en nyckel tar man bort ett konto.

Som jag resonerade var att kontot är så starkt knutet till **en** nyckel. Har man ingen nyckel behöver man inget konto, och det går snabbt att skapa upp ett nytt om man behöver det. Vilket lättar upp databasen och användare slipper hålla reda på konton. 

Men ska man tillåta flera nycklar per användare så skapar det problem.

Men så som jag läser kriterierna för uppgiften så ska det vara okej att göra så här.

**Comment by Guepen** [comment]
man har CRUD på både användare och API-nycklar. Om man ändrar/tar bort nyckeln så finns användaren kvar när jag testar i alla fall. Man var väl även fri att utöka kraven?

**Comment by 1dv450** [comment]
:+1:
