### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by ib222dp** [th222fa/1DV450_APIRegistration#7]
1. Enligt detta stycke:
   https://www.railstutorial.org/book/modeling_users#sec-uniqueness_validation 
   måste man sätta index på de värden som ska vara unika för att "validates uniqueness" verkligen ska fungera. Därför borde det vara index på users: email och users: username och apikeys: key.
2. Det hade varit smidigt att ha en länk till inloggningsformuläret för administratörer.
3. Eftersom det är en användare som har en API-nyckel (user has_one apikey) känns kodraden   "apikey.user = @user" i metoden create i users_controller lite onaturlig. Är det inte mer logiskt med @user.apikey = key?
4. Jag var tvungen att köra rails server -b, binding=0.0.0.0 (alltså inte bara rails server) för att kunna testköra i Nitrous, så det skulle du kunna utöka din installationsbeskrivning med.

**Comment by Guepen** [comment]
när jag testar applikationen så fungerar valideringen för uniqueness men kan ju vara bra att lägga till för att vara säker.

Jag valde att inte ha någon länk till admin för att öka säkerheten. Nu vet ju inte möjliga hackers att det finns en separat inloggning för admin

Håller med om att det borde user.apikey men fick inte det att fungera... Som jag har det nu så fungerar det i alla fall :) 

Ska lägga till informationen för Nitrous
