### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ib222dp** [th222fa/1DV450_APIRegistration#8]
Installationsbeskrivningen är tydlig och utförlig. Applikationen har på det stora hela en bra gränssnittsdesign. Validering av registrering och inloggning för användare och administratörer fungerar bra, förutom bekräftelse av lösenord. Bra att både användarnamn och epost måste vara unika. Koden har bra struktur och är lätt att förstå.

**Comment by Guepen** [comment]
Tack för givande feedback :)
