### ISSUE TITLE
Allmän feedback

### ISSUE THREAD

**Issue by WheresMarco** [th222fa/1DV450_APIRegistration#9]
Efter att ha kollat igenom applikationen så tycker jag den är enkel att installera. Följde dina instruktioner och det fungerade utan problem.

Kan tycka att det var förvirrande att ha admin-inloggningen separat från den för användare men det hänger ihop att du använder Active Admin. Lägger man till fler inställningar kan det vara helt naturligt att dela upp det så.

Du har lite felmeddelanden som dyker upp som inte är så roliga när man t.ex. försöker radera en nyckel. Route:sen sitter fel, men jag vet inte riktigt vart dom ska peka. Hittar ingen controller för nycklarna och ingen destroy-metod i `User` som skulle kunna ta hand om det. Behöver fixas.

Annars sitter grunderna på plats.

**Comment by Guepen** [comment]
Skönt att det fungerade smärtfritt att köra igång applikationen!

tänkte lite på säkerheten för admin. Eftersom jag inte har länkat till någon admin och admin-inloggningen är separat kan den få möjliga hackers att tro att man loggar in som admin i den vanliga inloggen

Hade missat att pusha upp controllern för API-nyckel....

Tack för givande feedback!
